### PR TITLE
Fixes Issue 11

### LINKED ISSUE #3: Endnote 12
狐優 should be 狐偃

### LINKED ISSUE #11: Endnote 36
戰鬪大甲兵法 -> 戰鬭大甲兵法

### PR DESCRIPTION
**Pull request by thewchan**
Fixes #11

### CODE REVIEW

**Comment by acabal** [comment]
This has merge conflicts when rebasing, can you fix those?

**Comment by thewchan** [comment]
On my end it says "This branch has no conflicts with the base branch"? How do I check what you're seeing @acabal ?

**Comment by acabal** [comment]
First pull the master branch to get the latest version, then checkout this branch and do `git rebase master` which should highlight some conflicts. When they're fixed `git push -f` to github.

**Comment by thewchan** [comment]
Gotcha; it should be okay now? Sorry, learning as I go...

**Comment by acabal** [comment]
Looks good, thanks!

**Pull request merged**
