### PR TITLE
Issue #3: Endnote 12; 狐優 -> 狐偃

### LINKED ISSUE #3: Endnote 12
狐優 should be 狐偃

### PR DESCRIPTION
**Pull request by thewchan**
Fixes #3

### CODE REVIEW

**Comment by thewchan** [comment]
Fixes #4

**Comment by thewchan** [comment]
Fixes #5

**Comment by thewchan** [comment]
Fix #7

**Comment by thewchan** [comment]
Fixes #8

**Comment by thewchan** [comment]
Fixes #9

**Comment by thewchan** [comment]
Fixes #10

**Comment by acabal** [comment]
Excellent, thanks!

**Pull request merged**
